enable: true
account:
  token: 你的登录凭证
  uid: '210900388'
target:
  server_id: '5602523726001426'
  channel_id: '9968276418507561'
whitelist:
  users: []
rules:
- enabled: true
  keywords:
  - 空闲扣
  replies:
  - '3'
  reply_mode: fixed
  cooldown: 0
  priority: 0
  users: []
  name: rule_1789311674343_1
behavior:
  per_user_cooldown: 5
  global_rate: 30
  quiet_hours: []
  ignore_prefix:
  - /
  ignore_bots: true
  ignore_system: true
logging:
  hit_log: true
  log_file: hits.log
network:
  reconnect: true
  reconnect_backoff:
  - 1
  - 60
  notify_on_disconnect: true
  verify_channel_on_start: true
